---

- name: WordPress archive file exists?
  stat:
    path: "/tmp/wordpress.tar.gz"
  register: wordpress_downloaded

- name: Download Wordpress 
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  when: wordpress_downloaded.stat.exists == False

- name: Extract Wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz 
    dest: /tmp
  when: wordpress_downloaded.stat.exists == False

- name: set file permissions
  command: chown -R www-data:www-data /tmp/wordpress
  when: wordpress_downloaded.stat.exists == False

- name: sync WordPress into place
  synchronize:
    src: /tmp/wordpress/
    dest: "{{web_root}}"
    group: yes
    owner: yes
   
- name: copy sample config file
  copy:
    src: "{{web_root}}/wp-config-sample.php"
    dest: "{{vhost_path}}/wp-config.php"
  
- name: Update WordPress config file
  lineinfile:
    dest: "{{vhost_path}}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
